### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by Adaptivity**
Most modules translated. Will complete the others in the next PRs when I have more time. Now waiting for message localization :)

### CODE REVIEW

**Comment by MachineMuse** [comment]
Thanks muchly :)

**Comment by Adaptivity** [comment]
I'm also going to ping some people which can help with translations: @Vexatos @ReneMuetti @Mazdallier @AegisLesha @EzerArch @crafteverywhere @bakaxyf

**Comment by bakaxyf** [comment]
@3tusk will update Chinese translation :)

**Comment by Adaptivity** [comment]
Hmm, I also can ping @malangbalam and @alvin137 for ko_KR translation

**Comment by 3TUSK** [comment]
@bakaxyf Simplified Chinese translation merged. Anyone knows those guys who work on Traditional Chinese translation?

**Comment by EzerArch** [comment]
Is there something new in the EN lang?

**Comment by 3TUSK** [comment]
@EzerArch Check [this branch](https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/resources/assets/powersuits/lang/en_US.lang)

**Comment by EzerArch** [comment]
> @EzerArch Check this branch

Oh... there's a different branch. Ty.

**Comment by malangbalam** [comment]
ko_KR represents Korean
I'll get it done some time soon

**Comment by Mazdallier** [comment]
thanks to AegisLesha. merci d'avoir traduit durant Aout.

**Comment by 3TUSK** [comment]
I'd like to mark #623 and #624 here for reference.

**Pull request merged**
