### PR TITLE
Added Recipes for GregTech 5 (and Maybe GT 6)

### PR DESCRIPTION
**Pull request by florian96**
Based on the Old 1.6.4 Recipes. A little bit Modified.

### CODE REVIEW

**Comment by florian96** [comment]
You told me last year, I should do a pull request for GT recipes. And here he is.

**Comment by Xen1290** [comment]
Very good! But I can only see gt5 recipes. Have you tested those recipes?

**Comment by florian96** [comment]
It is with GregTech 5 (1.7.10) Tested. Tomorrow i Try it with GregTech 6 (1.7.10). i can say you, if it works.

Sorry for my bad english.

**Comment by florian96** [comment]
I have Tryed it now. But it do not work with GregTech 6. I Make a MPS-GT6 file latter in a New pull Request.

**Pull request merged**
