### PR TITLE
MPSA merged

### PR DESCRIPTION
**Pull request by lehjr**
Pretty much everything working but might need a bit of cleanup or tweaking. Someone else will need to do the language files and recipes.

Side note. I moved the water meter to next to the heat meter so they are all in the same row now.

### CODE REVIEW

**Comment by lehjr** [comment]
I have a newer version of the AE2 and EC2 modules for AE2-RV3 here: https://github.com/lehjr/ModularPowersuitsAddons/tree/QMX-master/src/main/java/com/qmxtech/powersuitaddons/modules

**Comment by Xen1290** [comment]
Wow! Very good work!
Just some things:
- Instead of add another GUI for crafting table, you can use directly the one already included in minecraft.
- You left some debug things , change the logger from: System.out.println to:  MuseLogger.logDebug("text"), here:
 src/main/scala/net/machinemuse/general/gui/frame/PortableCraftingContainer.java
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-53fb5a2430d50e50f5c3f0aad4466ed9R126
- On src/main/scala/net/machinemuse/powersuits/common/ModCompatibility.java , src/main/scala/net/machinemuse/powersuits/powermodule/tool/OmniProbeModule.java and https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-53fb5a2430d50e50f5c3f0aad4466ed9R127
instead of using : 
 if (Loader.isModLoaded("EnderIO") etc
You should use isEnderIOLoaded, like the other mods done in ModCompatibility.java. I hope you understand what I mean.
- https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-d85c4bd1a7efee246070ce8d4568bdbfR29 I think the mod should be only one, not two?
@lehjr @MachineMuse 
And.. I can't see gradle/dev envir changes, it's normal?

**Comment by lehjr** [comment]
For the portable crafting setup, I used the code that MPSA had. It worked and I didn't want to mess with that.

Not sure what you meant here: 
"https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-d85c4bd1a7efee246070ce8d4568bdbfR29 I think the mod should be only one, not two?"

This maybe? 
var modid = "powersuitaddons"; ? 

LOL, oops. That was something I did early on to get things working. 

Great catches.

I didn't include the changes for build.gradle because the only major change is for using Intellij instead of eclipse. The issue with trying to run with 2 different versions of chisel is more of an issue with the code of the mod itself trying to support 2 conflicting mods. The Smart Render bug is an issue not easily solved. It comes with a GPLv3 license, but without the source code needed to comply with it.

**Comment by Xen1290** [comment]
Oh sorry:
For crafting tables, the only thing to do is change asset path.
And yes, I meant var modid = "powersuitaddons";
For the third thing, for now I think we should wait MachineMuse.

**Comment by lehjr** [comment]
For the smart render bug, turns out not only is the code available in the smart moving zip, but the version in there doesn't appear to have the bug. The dev version in there doesn't have it.

**Comment by MachineMuse** [comment]
Amazing! Thanks for your hard work.

I just got an apartment today so I'll be moving into it and then building a new computer - should be able to  take a proper look & test and things maybe this weekend or next week sometime.

**Comment by lehjr** [comment]
Most everything seems to be working, but I'm sure it will need a bit of spit and polish. One thing I did notice is that the meters seem to only be working in a dev environment.

**Comment by Xen1290** [comment]
You missed some lines @lehjr :
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-b532297167ca0e3be3b0b1dddf7fc72bR144
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR54
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR59
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR70
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR65
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR116
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR122
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR127
https://github.com/MachineMuse/MachineMusePowersuits/pull/632/files#diff-45ca2cfb175eba20bb1871f5c0fbc4edR142

**Comment by lehjr** [comment]
@Xen1290 I have no idea what you are referring to there.

**Comment by Xen1290** [comment]
https://github.com/lehjr/MachineMusePowersuits/commit/2380b53f36148d9249d2d06a63d6d9d9cdbc8177#diff-b532297167ca0e3be3b0b1dddf7fc72bR143
Typo: isCompactMachinesLaded() --> isCompactMachinesLoaded

**Comment by lehjr** [comment]
@Xen1290 Thanks again!

**Comment by Xen1290** [comment]
:+1:

**Comment by lehjr** [comment]
Almost. I did find a couple of other things I need to update

**Comment by Xen1290** [comment]
Any news @MachineMuse ?

**Comment by lehjr** [comment]
@Xen1290 Patience, Grasshopper. She's probably still settling in and building a Windows based computer or just waiting for internet. Meanwhile, I can upload a build from the current source if you want to use it. However, I won't be able to fix anything more for a couple weeks.

**Comment by Xen1290** [comment]
@lehjr I'm very patient,you misunderstood,but in fact I wanted a test build to test it a little and prepare the new recipes and help MachineMuse some you to find any bugs :) , that's all , I'm not one of them that ask every 3 second ETA,rather I'm against these attitudes  :+1: so, if you can upload a build I can test it for you and make the new recipes
Sorry for possible english mistakes, i hope you have understood.

**Comment by lehjr** [comment]
I'll be uploading 2 builds today. 1 will be for Applied Energistics rv2 and
the other for rv3

**Comment by lehjr** [comment]
I've uploaded a version for AE2 RV2 and one for RV3 at https://github.com/lehjr/MachineMusePowersuits/releases

Just remember that they are experimental, so back up any world you don't want to lose.

**Comment by Xen1290** [comment]
Thanks! I'll test

**Comment by lehjr** [comment]
@Xen1290 Other than the recipes and issues not already reported, have you found anything else? I'm away from home for the next few days but I want to see if anything else needs to be fixed. If not, maybe I'll dig into those power issues when I get back.

**Comment by Xen1290** [comment]
As far as I tested, everything works, but with the power issues, I can't test some things.

**Comment by lehjr** [comment]
Thanks. I usually charge up with EnderIO's wireless charger so I wasn't
even aware of the issues until I looked at the bug reports

**Comment by lehjr** [comment]
@MachineMuse you still out there somewhere?

**Comment by flowtender** [comment]
Hello,

Yes, I am still out there! I've been very busy, sorry T_T I will do my best to get on this soon.

**Comment by flowtender** [comment]
I wish you would make separate branches for each fix instead of merging all of them into one mega-pullrequest ^^' Whatever, I'll merge this and then we can deal with the fallout

**Pull request merged**
