### PR TITLE
Recipes Update

### PR DESCRIPTION
**Pull request by Xen1290**
Added the missing recipes for MPSA and fixed some things, added ore dictionary support when possible.
Please give me some feedback before merging.
Also reordered the recipes order.
@MachineMuse
Please merge.

### CODE REVIEW

**Comment by lehjr** [comment]
Great! This really needs to get merged before anything else.

**Comment by flowtender** [comment]
thanks! sorry for the wait :)

**Comment by flowtender** [comment]
I do have some balance concerns about the previous enderIO recipes but I wasn't sure who to bug about them and didn't really want to fix them myself. I'll have to look at these ones too @_@

**Comment by Xen1290** [comment]
Let me know what you would change, I'll do it for you.

**Comment by Xen1290** [comment]
I've been more strict with Thermal Expansion and Ender IO recipes, because these mods are really easy.

**Pull request merged**
