### PR TITLE
Fix for Hard to break certain blocks #628

### PR DESCRIPTION
**Pull request by lehjr**
Initially, I thought there was something wrong with the code because I could only harvest tracks while in a dev environment but not in a normal game. Turns out the harvest tool changes and becomes a crowbar, which the PowerFist implements through the Omniwrench module. Hardness checks could not be used because of the coordinate requirements needed for getting a blocks hardness. The code for the Axe and Shovel modules are almost the same but using the same code for the pickaxe module would have made the diamond upgrade module obsolete.

### CODE REVIEW

**Comment by eyeonus** [comment]
Two things:
1) Shouldn't that block checking code be in IBlockBreakingModule, so it can be used by any module, including those that do not currently but may exist in future, without needing to bloat the code by copying it?

2) Doesn't the diamond drill upgrade also need that code since it overrides the base code of the pickaxe?

I worked on this, it needs testing, because I don't have a dev environment or the desire to set one up, but the following should not only work fine, but also be easily extendable to other modules with block breaking capabilities:

src/main/scala/net/machinemuse/api/moduletrigger/IBlockBreakingModule.java:

``` java
    private static string isEffectiveHarvestTool(Block block, int metadata, ItemStack emulatedTool) {
        String effectiveTool = block.getHarvestTool(metadata);
        if (emulatedTool.getItem().canHarvestBlock(block, emulatedTool)) {
            if (effectiveTool == "pickaxe") {
                return effectiveTool+Integer.toString(block.getHarvestLevel(metadata));
            }
            return effectiveTool;
        }

        // some blocks like stairs do no not have a tool assigned to them
        if (effectiveTool == null) {
           if (emulatedTool.func_150997_a/*getStrVsBlock*/(block) >= ((ItemTool) emulatedTool.getItem()).func_150913_i/*getToolMaterial*/().getEfficiencyOnProperMaterial()) {
               /* ItemStack.toString() returns a string in the form "nnxitem.NAME@dd",
                  where nn is the number of items in the stack, NAME is the name of the
                  item, and dd is the damage of the item. The following line returns just
                  the NAME portion. Ex.: 1xitem.pickaxewood@25 -> pickaxewood */
               return emulatedTool.toString().substring( emulatedTool.toString().indexOf("item.")+5 , emulatedTool.toString().indexOf("@") );
           }
        }
        return effectiveTool;
    }
```

---

src/main/scala/net/machinemuse/powersuits/powermodule/tool/ShovelModule.java:

``` java
     public boolean canHarvestBlock(ItemStack stack, Block block, int meta, EntityPlayer player) {
        if (isEffectiveHarvestTool(block, meta, new ItemStack(Items.iron_shovel) ).indexOf("shovel") != -1) {
             if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, SHOVEL_ENERGY_CONSUMPTION)) {
                 return true;
             }
         }
         return false;
     }
```

---

src/main/scala/net/machinemuse/powersuits/powermodule/tool/PickaxeModule.java:

``` java
     public static boolean harvestCheck(ItemStack stack, Block block, int meta, EntityPlayer player) {
         String result = isEffectiveHarvestTool(block, meta, new ItemStack(Items.iron_pickaxe) )
         if (result.indexOf("pickaxe") != -1 && Integer.parseInt(result.substring(result.length() -1)) < 3) {
             if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, PICKAXE_ENERGY_CONSUMPTION)) {
                 return true;
             }
         }
         return false;
     }
```

---

src/main/scala/net/machinemuse/powersuits/powermodule/tool/AxeModule.java:

``` java
     public boolean canHarvestBlock(ItemStack stack, Block block, int meta, EntityPlayer player) {
        if (isEffectiveHarvestTool(block, meta, new ItemStack(Items.iron_axe) ).indexOf("axe") != -1) {
              if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, AXE_ENERGY_CONSUMPTION)) {
                  return true;
              }
         }
         return false;
     }  
```

**Comment by lehjr** [comment]
The API shouldn't contain any working code. Think of it more as a header file in C or C++. That said, it could have been placed in a common area for both the axe and shovel modules to use, but I didn't do that simply because it is only useful for those 2 modules. The pickaxe requires different code because while a an axe or shovel of any material type will harvest their intended blocks, the pickaxe category is split between 2 modules, 1 emulating an iron pickaxe and the other a diamond one. As to why the diamond pickaxe doesn't need the code, there are very few blocks that it is needed for, the only one of which I can think of is obsidian which already passes the check in the current code. 

Also, keep in mind that the harvest checks are done sequentially from each installed IBlockBreaking module: https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/item/ItemPowerFist.scala#L240

**Comment by eyeonus** [comment]
I just thought it was rather untidy to have basically the same code in three places where it could be in just one. The "isEffectiveHarvestTool" method I have can be used by anything that breaks blocks, even if it does need to be somewhere else. Wasn't aware that was part of the API

**Comment by lehjr** [comment]
It is untidy. It's just the result of getting sick of looking at it after several different approaches and  a bit of a rush to get something out that people can use right away since it has been broken long enough. 

What would be better than all of it as it is would be to call isEffectiveHarvestTool to check which module to use, then it's only called once. As it is right now, both your version and mine will call it in each module. 

However, there's still a matter of the interaction with the Treecapitator mod, and all of this might be for nothing if it has to get rewritten again.

**Comment by eyeonus** [comment]
Okay.
How's this?

``` java
    //Returns true if tool is effective, otherwise false.
    private static boolean isEffectiveHarvestTool(
        Block block,
        int metadata,
        ItemStack testTool
    ) {
        return (testTool.func_150997_a/*getStrVsBlock*/(block) >= ((ItemTool) testTool.getItem()).func_150913_i/*getToolMaterial*/().getEfficiencyOnProperMaterial())
    }

    //Returns string of all effective testTools
    private static String toolTest (Block block, int metadata) {
/**/
//----  This is what we want to replace.            
        //Name of the types of tools we want to test with.
        String[] testTools = {
            "pickaxe",
            "axe",
            "shovel"
        };

        //Iron tools of the types in testTools, in the same order.
        ItemStack[] tools = {
            new ItemStack(Items.iron_pickaxe),
            new ItemStack(Items.iron_axe),
            new ItemStack(Items.iron_shovel)
        };
//----
/**/
/*
//----  This is what we want to replace it with.
//----  This probably doesn't work, don't feel like looking up how to make it work.
//----  Important bit is formatting: easier than keeping tabs on two separate lists.
        // Name of the types of tools we want to test with,
        // with example Iron tool of type for testing.          
        Object[String, ItemStack] testTools = {
            {"pickaxe", new ItemStack(Items.iron_pickaxe)},
            {    "axe", new ItemStack(Items.iron_axe)},
            { "shovel", new ItemStack(Items.iron_shovel)}
        };
//----
*/
        String effectiveTool = null;

        // Tests each of testTool[]'s example tools,
        // appends them to effectiveTool if they can harvest the block.
        for(int i = 0; i < testTools.length(); x+=1  {
            if (isEffectiveHarvestTool(block, meta, tools[i]))
                effectiveTool += testTools[i];
        }
        return effectiveTool;
    }

    //Returns the block's HarvestTool if it exists, or returns the results of testTools,
    // appending the pickaxe harvest level if pickaxe is effective.
    private static string getEffectiveTool(Block block, int metadata) {
        String effectiveTool = block.getHarvestTool(metadata);

        //Block doesn't tell us what tool works, so now we have to test it.
        if (effectiveTool == null) {
            effectiveTool = toolTest(block, metadata);
        }
        if (effectiveTool.indexOf("pickaxe") != -1) {
            effectiveTool+=Integer.toString(block.getHarvestLevel(metadata));
        }
        return effectiveTool;
    }
```

isEffectiveHarvestTool(block, metadata, testTool) returns true if tool being tested is effective, otherwise returns null. Is used by toolTest() to perform the testing.
It's literally a simply named wrapper around a specific test from the WAILA code.

toolTest(block, metadata) returns a string containing all the types of tools that are effective.
Currently tests pickaxe, axe, and shovel, can return from null to "pickaxeaxeshovel".

getEffectiveTool(block, metadata) returns the block's HarvestTool if it exists, or returns the results of toolTest(), appending the pickaxe harvest level if pickaxe is effective.
Example results are "axe", "shovel", "pickaxeN", where N (0-9) is harvest level.

getEffectiveTool() does the block.getHarvestTool() thing where you get back a string saying what type of tool works on the block, but when that fails it'll spit back a string saying all the tools being tested that worked so you can easily find if the one you want is in there. It also gives you the harvest level for pickaxes, which is easily taken advantage of:

``` java
//Pickaxe check
     public static boolean harvestCheck(ItemStack stack, Block block, int meta, EntityPlayer player) {
         String result = getEffectiveTool(block, meta);
         //Does the result contain "pickaxe" in it and is the harvest level 2 or lower?
         if (result.indexOf("pickaxe") != -1 && Integer.parseInt(result.substring(result.length() -1)) < 3) {
             if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, PICKAXE_ENERGY_CONSUMPTION)) {
                 return true;
             }
         }
         return false;
     }
```

``` java
//Axe check
     public boolean canHarvestBlock(ItemStack stack, Block block, int meta, EntityPlayer player) {
        if (getEffectiveTool(block, meta).indexOf("axe") != -1) {
              if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, AXE_ENERGY_CONSUMPTION)) {
                  return true;
              }
         }
         return false;
     }  
```

``` java
//Shovel check
     public boolean canHarvestBlock(ItemStack stack, Block block, int meta, EntityPlayer player) {
        if (getEffectiveTool(block, meta).indexOf("shovel") != -1) {
             if (ElectricItemUtils.getPlayerEnergy(player) > ModuleManager.computeModularProperty(stack, SHOVEL_ENERGY_CONSUMPTION)) {
                 return true;
             }
         }
         return false;
     }
```

**Comment by eyeonus** [comment]
Regarding the diamond upgrade, I thought it needed that test as well because there are items higher than Diamond in some mods. I'm thinking specifically of Tinker's Construct, but other mods do as well.

If the intent is for the diamond upgrade to be the I-can-pickaxe-ANYTHING upgrade, then I can see why it wouldn't need that kind of test.

**Comment by eyeonus** [comment]
You could also use getEffectiveTool() to figure out which module to call:

``` java
    result = getEffectiveTool( block, meta);
    if (result.indexOf("pickaxe") != -1 &&
      Integer.parseInt(result.substring(result.length() - 1)) < 3) {
        //Do the pickaxe module stuff.
        result = null; //Make sure it doesn't trigger the others.
    }
    if (result.indexOf("axe") != -1) {
        //Do the axe module stuff.
        result = null;
    }
    if (result.indexOf("shovel") != -1) {
        //Do the shovel module stuff.
        result = null;
    }
//etc..
```

**Comment by flowtender** [comment]
We can do it this way for now. Scala has a construct called Traits (mixins) which would do what aionys is suggesting, but that will be some conversion & refactoring effort.

**Comment by flowtender** [comment]
The diamond drill upgrade is a bit of a tough problem since it was added before mods started having harvest levels higher than 3. It would be great to have MPS automatically generate modules for each harvest level that is in use, but that'd require some magic or foresight that even I would balk at :P

**Comment by eyeonus** [comment]
How about, instead of a diamond drill-esque upgrade for every harvest level, a force field generator with configurable harvest level, with higher levels requiring more power to use, similar to the armor?

If you base it at one higher than diamond, and max it at 9, that should cover any material with a single digit. Could do more digits too, I'd just need to change the pickaxe bit in getEffectiveTool().

**Comment by lehjr** [comment]
I was thinking of calling the tool checking from within the PowerFist's canHarvest method to reduce the overhead of looping multiple times. However, I don't know if the overhead it saves is worth it, and I'm not entirely sure that it is the canHarvest methods in the modules are only called by from the PowerFist canHarvest method. While I was playing with the WAILA Harvest tool mod, I noticed that hovering over certain objects caused the canHarvest method in the pickaxe module to be called continuously, but not in other modules.

I'll come back to this and clean it up after I figure out how to fix the interaction with the Treecapitator mod.

**Comment by flowtender** [comment]
> I don't know if the overhead it saves is worth it,

It's not. The expensive logic still needs to be executed for each virtual item.

> I noticed that hovering over certain objects caused the canHarvest method in the pickaxe module to be called continuously, but not in other modules.

IIRC It exits the loop if it finds a module that can harvest the block in question, so this would happen when you're pointing at blocks that can be harvested by a pickaxe?

**Comment by lehjr** [comment]
i'm pretty sure that was the case, but I didn't notice it happening with other modules when looking at things like the ground or trees. I didn't really spend a lot of time on it though.

**Comment by EzerArch** [comment]
Just tried the new builds. Let me express my feelings about it:

_I can break EVERYTHING _~echo~_._ Including those pesky Mekanism reinforced blocks.

Thank you! :)

**Pull request merged**
