### PR TITLE
Fixed Tinker Table's crafting

### PR DESCRIPTION
**Pull request by chack1172**
Fixed the crafting of the block Tinker Table

### CODE REVIEW

**Comment by lehjr** [comment]
this should actually be "oredictName" : "itemMachineChassi"
and the experimental branch is not being updated. All updates are being done on the Java ports only. I'm done trying to work with Scala.

**Comment by chack1172** [comment]
"itemMachineChassis" or "itemMachineChassi"?
With the first I can't craft it using Machine Chassis and NEI doesn't show me the crafting.

**Comment by lehjr** [comment]
the second one. The first was a typo in the recipe.

**Comment by chack1172** [comment]
It doesn't work also with the second one. For now I use the code that I sent in the pull request.

**Comment by lehjr** [comment]
What version of enderio?

**Comment by chack1172** [comment]
1.7.10 2.2.8.381

**Comment by lehjr** [comment]
I've tried to avoid using the old versions of mods, since trying to mix and match old and new versions never ends well. Anyway, did you try ""itemMachineChassi" as a "registryName" or as an "oredictName"

**Comment by chack1172** [comment]
as oredictName

**Comment by lehjr** [comment]
I'm using it with EnderCore-1.7.10-0.2.0.39_beta and it works, but it might be better to just use the registry name if it isn't version specific. 

```
	{
		"ingredients" : [
			[ null, { "oredictName" : "gemEmerald" }, null ],
			[ { "oredictName" : "ingotElectricalSteel"}, { "registryName" : "EnderIO:itemBasicCapacitor" }, { "oredictName" : "ingotElectricalSteel"} ],
			[ null, { "oredictName" : "itemMachineChassi" }, null ]
		],
		"result" : {
			"registryName" : "powersuits:tile.tinkerTable"
		}
	},
```

**Comment by lehjr** [comment]
Anyway, just submit a PR for the java branch with the recipe as you have it and I'll put it there.

**Comment by chack1172** [comment]
I have the same version of EnderCore and I can't craft the tinker table with your crafting ahahah

**Pull request closed without merging**
