### PR TITLE
Fix minimum Numina version, update forge version, partial fix for leaf blower

### PR DESCRIPTION
**Pull request by lehjr**

### CODE REVIEW

**Comment by flowtender** [comment]
looks good!

**Comment by flowtender** [comment]
Is it necessary for the forge version to be incremented? I like to leave the forge version as low as possible in case other mods are broken in newer versions, to ensure backwards compatibility. But if you are using a new feature in Forge 1558 then it's inevitable.

**Comment by lehjr** [comment]
I went with the recommended version with the hopes that if there were any issues, they'd show up at build time rather than getting several reports later on, not that it won't happen anyway. But yeah, I know, it's tough sometimes when certain dependencies are updated faster than others. Most of the Forge updates seem to be nothing more than "busy work" anyway, but a few are useful.

**Comment by Tyler799** [comment]
THANK YOU! :D

Looks like the only things the leafblower doesn't figure out are Biomes A Plenty grasses/flowers and the tall versions of Botania flowers. (Which don't drop anything anyways, which is weird).

**Comment by lehjr** [comment]
Also doesn't touch BluePower flowers. Unfortunately, adding more things gets harder because of the load time and amount of RAM it takes. ATM, I'm running with about a 2 minute load time and close to maxing out on system memory, which isn't bad until you want to test several small changes until you figure out the best way of doing something.

**Comment by Tyler799** [comment]
Do you mean to load the game in general? With just MPS? Cause I can't imagine it adds much of anything to the load time. I've got nearly 200 I think in my FTB Infinity pack (plus a couple extras). The load times suck, but it's well worth it. To reduce it a bit, I just took out stuff I didn't use (Decorocraft, chisel II, hats, etc, any decorative stuff). That offsets anything I need to add.

**Comment by lehjr** [comment]
In a development environment, there's no such thing as just MPS. Every mod that it supports is also loaded on top of the overhead of the IDE itself. Running the game to simply play it isn't the same as testing changes. When you load the game to play it, you load it once and play until you're done. In a dev environment, you make a change to the code, launch the game, test whatever you were working on, shut it down and repeat or move on to the next thing.

**Pull request merged**
