### PR TITLE
fix "runClient" and set it's runtime ram to 3G.

### PR DESCRIPTION
**Pull request by arnesacnussem**
fix "runClient" and set it's runtime ram to 3G.
except EnderIO...i really don't know how add those runtime dependency
but you can add those two jar files to "run/mods" to make that mod works.

### CODE REVIEW

**Comment by lehjr** [comment]
There's a reason memory is set as high as it is.

**Comment by arnesacnussem** [comment]
@lehjr in fact , the default one is just not enough while run with EnderIO ,  2G should work properly,but it constantly end with OOM.
for me, i simply have that much ram...:joy:

**Comment by lehjr** [comment]
3GB is not enough when adding in all of the mods for testing.

**Comment by arnesacnussem** [comment]
maybe ,but......why not set that value yourself:fearful: 

the default value is a little more than 1700M

**Comment by lehjr** [comment]
because I'm the one doing 99.9% of the work on the mod

**Comment by lehjr** [comment]
and when the server has a 5 minute load time, I can't be screwing around with out of memory errors

**Comment by arnesacnussem** [comment]
my poor English told me you have oom problem....
so now it solved :smile:.......?

**Comment by lehjr** [comment]
depends on what I'm testing. For larger test cases, I just build it and run it in MultiMC. I have one instance that I've had to give 9GB.

**Comment by arnesacnussem** [comment]
i only test codes with IDEA, now it's easier for me. (that's why i fix the gradle dependencies,also can use travis-ci to make nightly build)

**Comment by lehjr** [comment]
For small changes IDEA is enough, there are cases where more testing is needed, especially in the case of Galacticraft + addons, Advanced Rocketry, and a few others. Not to mention that some testing is needed outside of the development environment just to make sure things work outside of the development environment.

**Comment by arnesacnussem** [comment]
learn to microsoft:_we only  need issue tracker_ ...(and keep alive)

**Comment by lehjr** [comment]
Windows is a virus.

**Comment by eyeonus** [comment]
Agreed. A pernicious, invasive, and annoying one, at that.

**Pull request merged**
